### ISSUE TITLE
dev-server on npm

### ISSUE THREAD

**Issue by PatrickJS** [langpavel/node-dev-server#1]
do you mind giving up `dev-server` on npm?

**Comment by bradisbell** [comment]
@langpavel As this package isn't maintained, would you please consider dropping the generic name to make way for other packages?

@gdi2290 have you heard from the author of this package since your last post a couple years ago?  And, do you still intend to use this package name if it is freed?  We can always contact support@npmjs.com as indicated by https://docs.npmjs.com/misc/disputes.html if we cannot contact the author.

**Comment by langpavel** [comment]
Hi. At first, what intent you have with `dev-server` ? 
I can extend it in the way which fits for all, but I will not give a package name without any good reason
I'm using dev-server all the years and nobody had an idea, opened an issue or something.

No, I don't give up name because it's still my favorite static file server.

@gdi2290 @bradisbell Let's discuss about features you need, point me to different repository and all the needed ceremony, then I can make decision if :heart: package is in good hands…

**Comment by PatrickJS** [comment]
It has been awhile, the original intent was to create hybrid webpack dev server and static server as `dev-server`. I ended up using `webpack-serve` then eventually gave it to webpack-contrib which it looks like they stopped working on it
